"""Alembic environment. The database URL comes from the app's settings, so
migrations always target the same database the app uses."""
from __future__ import annotations

from alembic import context

from app import models  # noqa: F401  (registers every table on Base.metadata)
from app.core.db import Base, engine

target_metadata = Base.metadata


def include_object(obj, name, type_, reflected, compare_to):
    """Tables of the old tournament (decision_log, cycle_runs, ...) still sit
    in databases created before the lab. They are no longer mapped; without
    this, every autogenerated migration would propose dropping them — and
    their history with them."""
    if type_ == "table" and reflected and compare_to is None:
        return False
    return True


def run() -> None:
    connection = context.config.attributes.get("connection")
    if connection is not None:
        context.configure(connection=connection, target_metadata=target_metadata,
                          include_object=include_object, render_as_batch=True)
        with context.begin_transaction():
            context.run_migrations()
        return
    with engine.connect() as conn:
        context.configure(connection=conn, target_metadata=target_metadata,
                          include_object=include_object, render_as_batch=True)
        with context.begin_transaction():
            context.run_migrations()


run()
