"""baseline: the lab schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-25 00:35:37.983464
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('system_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kill_switch_engaged', sa.Boolean(), nullable=False),
    sa.Column('kill_switch_reason', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('engine', sa.String(length=20), nullable=False),
    sa.Column('variant_key', sa.String(length=4), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('parent_variant_id', sa.Integer(), nullable=True),
    sa.Column('promoted_at', sa.DateTime(), nullable=True),
    sa.Column('last_decision_on', sa.String(length=10), nullable=True),
    sa.Column('last_rebalance_on', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('scaled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_variant_id'], ['variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_variants_stage'), ['stage'], unique=False)

    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('start', sa.String(length=10), nullable=False),
    sa.Column('end', sa.String(length=10), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('series', sa.JSON(), nullable=False),
    sa.Column('trades', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backtest_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backtest_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_backtest_runs_variant_id'), ['variant_id'], unique=False)

    op.create_table('lab_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lab_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lab_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_events_variant_id'), ['variant_id'], unique=False)

    op.create_table('paper_portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('initial_cash', sa.Float(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('broker', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paper_portfolios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_portfolios_variant_id'), ['variant_id'], unique=True)

    op.create_table('paper_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('order_type', sa.String(length=10), nullable=False),
    sa.Column('limit_price', sa.Float(), nullable=True),
    sa.Column('stop_price', sa.Float(), nullable=True),
    sa.Column('time_in_force', sa.String(length=5), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('max_loss', sa.Float(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('broker', sa.String(length=20), nullable=False),
    sa.Column('broker_order_id', sa.String(length=64), nullable=True),
    sa.Column('exit_reason', sa.String(length=40), nullable=True),
    sa.Column('filled_qty', sa.Float(), nullable=False),
    sa.Column('filled_avg_price', sa.Float(), nullable=True),
    sa.Column('requested_price', sa.Float(), nullable=True),
    sa.Column('slippage_bps', sa.Float(), nullable=False),
    sa.Column('spread_bps', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['paper_portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paper_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_orders_broker_order_id'), ['broker_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_orders_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_orders_purpose'), ['purpose'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_orders_status'), ['status'], unique=False)

    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('as_of', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['paper_portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_snapshots_as_of'), ['as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_snapshots_portfolio_id'), ['portfolio_id'], unique=False)

    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('avg_entry_price', sa.Float(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['paper_portfolios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'symbol', name='uq_portfolio_symbol')
    )
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_positions_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_symbol'), ['symbol'], unique=False)

    op.create_table('execution_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('event', sa.String(length=40), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['paper_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('execution_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_events_order_id'), ['order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('execution_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_events_order_id'))

    op.drop_table('execution_events')
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_positions_symbol'))
        batch_op.drop_index(batch_op.f('ix_positions_portfolio_id'))

    op.drop_table('positions')
    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_snapshots_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_portfolio_snapshots_as_of'))

    op.drop_table('portfolio_snapshots')
    with op.batch_alter_table('paper_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_orders_status'))
        batch_op.drop_index(batch_op.f('ix_paper_orders_purpose'))
        batch_op.drop_index(batch_op.f('ix_paper_orders_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_paper_orders_broker_order_id'))

    op.drop_table('paper_orders')
    with op.batch_alter_table('paper_portfolios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_portfolios_variant_id'))

    op.drop_table('paper_portfolios')
    with op.batch_alter_table('lab_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lab_events_variant_id'))
        batch_op.drop_index(batch_op.f('ix_lab_events_created_at'))

    op.drop_table('lab_events')
    with op.batch_alter_table('backtest_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backtest_runs_variant_id'))
        batch_op.drop_index(batch_op.f('ix_backtest_runs_created_at'))

    op.drop_table('backtest_runs')
    with op.batch_alter_table('variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_variants_stage'))

    op.drop_table('variants')
    op.drop_table('system_state')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
